readme.md

`chatgpt-api` has been wrapped by a molecule.sh 's `molecule` to make it possible for [EXM](https://exm.dev) smart contracts to interact with ChatGPT
- example: https://github.com/decentldotland/molecule/blob/main/examples/chat-gpt/wtf.md

docs: add molecule.sh ChatGPT molecule

---

readme.md

Hi, I noticed the core logic for requesting ChatGPT API is take from my project, so I think it would be nice to add that to README. 😄

Add link to wong2/chat-gpt-google-extension

---

package.json

See https://github.com/mpociot/chatgpt-vscode/issues/1 for details. 
Putting default export as the last in package.json solves this problem.
Lots of people are having trouble getting chatgpt-vscode up and running because of this.

Fix "Error: Default condition should be last one" when package is used as a dependency

---

.github/workflows/test.yml
docs/classes/ChatGPTAPI.md
docs/classes/ChatGPTConversation.md
docs/modules.md
docs/readme.md
package.json
pnpm-lock.yaml
readme.md
src/chatgpt-api.test.ts
src/chatgpt-api.ts
src/chatgpt-conversation.ts
src/demo-conversation.ts
src/demo.ts
src/fetch-sse.ts
src/fetch.ts
src/index.ts
src/stream-async-iterable.ts
src/types.ts
tsup.config.ts

- adds support for native `fetch` on node.js >= 18
- removes `node-fetch`
- adds support for browser & edge runtimes
- uses `undici` as an optional dependency for node.js < 18
- refactors conversation support a bit
- adds the ability to use `AbortController` to cancel a ChatGPT `sendMessage` HTTP request
- removes support for node.js 14
- should be more robust now due to several HTTP-related fixes
- adds support for custom `accessTokenTTL`
- adds support for custom `timeoutMs` (which also aborts the underlying HTTP request upon a timeout)
Fixes #24, #33, and #16

Add support for native fetch; undici on node.js < 18

---

readme.md

Hi there!
I propose adding a link to [my fork](https://github.com/timkmecl/chatgpt-vscode) of the first vscode extension on the list of projects after it as an update, since the original hasn't been updated since `v0.4` of the api. I have added multiple improvements to the original:
- uses `api v1.4` with session token (and am planning on upgrading it to `v2.0` today)
- dispalys response word by word by using `onProgress` option
- multiple UX improvements over the original
- includes `.vsix` file of the extension in releases for quick installation
- extended readme (co-written by chatGPT as a bonus;) )

Update readme.md with an updated version of an extension

---

readme.md

added chatgpt on all platforms supported by Carik Bot (telegram, whatsapp, line, facebook messenger, discord, etc).

Add CarikBot to Projects

---

src/chatgpt-api.ts

In order to avoid encountering request frequency limits, or some other account errors, we need to implement some load balancing strategy, just like manage accounts stored in Redis or MongoDB. 
But if we manage tokens completely through this package, there will be at least one http request for authentication before each request.  It is difficult to build a distributed stateless restAPI service, so I put the accessToken parameter at the end and the default value is set to an empty string for compatibility.
PS: Especially in some areas where network connections are alway not that stable or the network speed is slow, it will cause higher latency and waste more time for waiting the answer from chatGPT.

feat: set accessToken while initialize ChatGPTAPI

---

docs/readme.md
readme.md

Fixed path for running demos in the docs from /src to /demos

Fixed demo paths in docs

---

readme.md

It's a shortcut version implemented by [chantgpt-api](https://github.com/transitive-bullshit/chatgpt-api)

docs: add project for chatgpt shortcut

---

src/openai-auth.ts

- Removes unnecessary console logging in `checkForChatGPTAtCapacity()`
- puts the alert message into the error message
My rationale for doing this is that the log messages can be confused with other messages from the user's actual program, which doesn't seem necessary in the first place. The capacity text that gets logged can be returned as part of the error message (which I've changed to do so in this PR), and since we're ignoring errors in the try-catch block anyway, there's no real point in logging it either.

fix: remove unnecessary console logging

---

src/chatgpt-api-browser.ts

Pressing Enter would normally send the current message, so now the code splits it up by newlines and uses Shift+Enter unless it's the last split.

fix: properly handle messages with newlines

---

src/chatgpt-api-browser.ts
src/openai-auth.ts

This PR introduces a new `browserOption` option for the `ChatGPTAPIBrowser` constructor, which allows users to specify the path to their preferred Chrome/Chromium executable for use with Puppeteer. If the `browserOption` value is defined, it will be used in place of the default path returned by `defaultChromeExecutablePath()`.
By providing this option, users have greater control over which browser is used to run Puppeteer, which can be useful in cases where the default executable path may not be correct or available on their system.
Closes #140

feat: Add browserPath option to ChatGPTAPIBrowser

---

.gitignore
package-lock.json
readme.md
src/chatgpt-api-browser.ts
src/openai-auth.ts

From the readme:
The browser implementation supports setting a proxy server. This is useful if you're running into rate limiting issues or if you want to use a proxy to hide your IP address.
To use a proxy, pass the `proxyServer` option to the `ChatGPTAPIBrowser` constructor, or simply set the `PROXY_SERVER` env var. For more information on the format, see [here](https://www.chromium.org/developers/design-documents/network-settings).
```ts
const api = new ChatGPTAPIBrowser({
email: process.env.OPENAI_EMAIL,
password: process.env.OPENAI_PASSWORD,
proxyServer: '<ip>:<port>'
})
```
You can also set the `PROXY_VALIDATE_IP` env var to your proxy's IP address. This will be used to validate that the proxy is working correctly, and will throw an error if it's not.

feat: add proxy support

---

src/openai-auth.ts

sometimes on my windows device the captcha will open before my long email is entered

fix: email input not complete

---

src/chatgpt-api-browser.ts

This PR fixes the the failure to retry a request upon encountering a 403 status code (more details on that in the commit description). Also includes other small fixes like the double call to refreshSession() on 403 as well, and improving refreshSession() by making sure the Cloudflare Anti-bot page has completed before returning, which in fact fixes another related bug due to the early return which causes getIsAuthenticated() to return false (false positive) due to the cloudflare anti-bot page still being present and thus resetting the session (unnecessary). Finally, I have added logging for the `cf_clearance` on initSession() and refreshSession().

Fix 403 handling during sendMessage & 

---

src/chatgpt-api.ts

As we allow the constructor to define completionParams, it would be better to allow devs using the library to use the specified stop token. As of right now, the library allows such stop to be passed but it isn't considered in the class itself.

chore: moving from im_end to completion params

---

readme.md

Hello!
Just adding the isomorphic-fetch to the options to work with node < 18, that was the only one that worked for me. 
Thanks !

Including isomorphic-fetch option for node < 18 to the README

---

src/openai-auth.ts

50ms of delay would likely to fail the login because button not loaded, so wait more.

Wait more on password prompt

---

readme.md

DomainGPT - Ask ChatGPT to suggest domain names for your startup and show available options
Demonstrate how to combine fuzzy suggestions with fact checking apis to make things more useful.
Hosted version: https://domaingpt.billylo.ca

add DomainGPT to list of interesting projects that uses chatGPT api

---

readme.md

Updated README.md documentation to correct spelling of `ChatGPTAPIBrowser ` which was previously `ChatGPAPIBrowser `, and also added a completing sentence to the code guide in README.md for the readers to understand the documentation well.

Fixed typo in README.md

---

readme.md

this lib does the same thing as the python implementation

Node JS lib to get chat gpt auth token to use with ChatGPTUnofficialProxyAPI

---

src/fetch-sse.ts

Currently, when stream is enabled the `fetchSSE` isn't returning the api response details.

Write the underlying exception details to streamed response

---

src/chatgpt-api.ts
src/types.ts

This PR simply exports the constructor options for the `ChatGPTAPI` class so it can be extended/used by other developers! I would rather use this type as a union for my wrapper classes rather than having to manually define it myself! Keep being awesome! Love how active this repo is
i.e.
```typescript
import { ChatGPTAPI, ChatGPTAPIOptions } from 'chatgpt';
type ChatGPTServiceOptions = ChatGPTAPIOptions & {
customOption: string;
}
class ChatGPTService {
api: ChatGPTAPI;
customOption: string;
constructor({ 
apiKey = process.env.OPENAI_API_KEY, 
customOption = '', 
...other 
}: Partial<ChatGPTServiceOptions> = {}) {
this.api = new ChatGPTAPI({
apiKey,
...other
});
this.customOption = customOption;
}
}
```

feat: exports init options for external use

---

src/chatgpt-api.ts

Fixing a typo in the default system message which sometimes causes weird problems, including failure to retrieve certain information. Additionally, using the official knowledge cutoff seems to help.
See Chanzhaoyu/chatgpt-web#242 for an example.

fix: use official system message by default

---

src/chatgpt-api.ts

The last content returned by the API may be without content, like this:
```json
{"id": "chatcmpl-6sCTfbTbepsgh2wvCX9x1gELH7Kdc", "object": "chat.completion.chunk", "created":1678375695, "model": "gpt-3.5-turbo-0301", "choices":[{"delta":{}, "index":0, "finish_reason": "stop"}]}
```
If the content is judged to exist or not, the `detail` information is lost, including the `finish_reason`.

fix: last detail lost

---

src/chatgpt-api.ts

There is an error in the prompt string concatenation in the original code
it is a mistake about `reduce`

fix: prompt string concatenation error

---

readme.md

Provide OpenAI API for services, and subsequently access more AI-related API

feat: add OpenAI-API-Service for readme

---

src/chatgpt-api.ts
src/types.ts

Resolves https://github.com/transitive-bullshit/chatgpt-api/issues/477
When making requests with `stream` mode (passing `onProgress()`) [we don't have access](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_stream_completions.ipynb) to the tokens `usage` object
Alternatively, we can calculate tokens `tiktoken` - tokenized that, as they say, itself used in ChatGPT. Actually, cahtgpt-api is already doing it for calculating allowed length of message history sent to ChatGPT. 
So the only thing I've added:
* calculated tokens of complete response in a streamed message
* added it to a message object before return to user
* added types for `ChatMessage.detail` to safely read those fields in TS

#477 Estimate tokens usage with streaming completions

---

src/chatgpt-api.ts
src/types.ts

Expect to specify `conversationId` in option of `sendMessage` , ChatGPTAPI .
So we can support multi-conversation chat。After message save,  query whole conversation infomation according to fieldname: `conversationId` from custom database,  rather than last message's `parentMessageId`.
In fact, there are serveral conversation in the same database(maybe mysql, mongodb), every message in one conversation should has  same identity, so that they can quickly be found / deleted。
Usage like:
```
sendMessage(text, { parentMessageId: PID, conversationId: MyConversationId })
```
Then query them:
```
// Get all message in specified conversation
mongoCollection.find({ conversationId: MyConversationId })
// Delete all message in specified conversation
mongoCollection.delete({ conversationId: …
```

Feat: support conversationId field in ChatGPTAPI.sendMessage option

---

src/chatgpt-unofficial-proxy-api.ts
src/fetch-sse.ts

The unofficial API actually returns `200 OK` and
```
{"detail":{"message":"Your authentication token has expired. Please try signing in again.","type":"invalid_request_error","param":null,"code":"token_expired"}
```

Handle possible token expired errors

---

readme.md

Cloudflare added new fingerprints and made my proxy impractical at scale.
Users can run https://github.com/linweiyuan/go-chatgpt-api locally instead or use public proxy by @pengzhile

Unofficial Proxy update

---

bin/cli.js

User may need to edit `apiBaseUrl` to use their service provider.
`apiBaseUrl` has already been defined in `ChatGPTAPI` but not in the command line option.
New option: `--host <host>`

feat(cli): add base url option
