transitive-bullshit/agentic

- src/chatgpt-api-types.ts
- src/index.ts
> feat: add typings for the ChatGPT API

- readme.md
Thanks for making chatgpt-api :)
> Add the ChatGPT Everywhere Chrome extension

- src/chatgpt-api.ts
- src/example.ts
Hey! I've added a new function which allows the user to reset the chat with the AI back to its initial state. I needed this function for one of the apps that I'm coding and I thought that could be good sending a PR
> Add resetThread() function

- readme.md
I created a Discord Bot with chatgpt package.
> Discord bot added to readme file

- readme.md
ChatGPT webchart bot is a WeChat assistant based on NodeJS and webchaty. This tool is more convenient for you to  use ChatGPT, you just chat with it as a good friend or a housekeeper.
> doc: add Wechat Bot to examples list

- readme.md
Hi there, I saw to create a PR if using this lib.
I created a VSCode extension using only ChatGPT outputs and minimal human intervention to create a ChatGPT integration.
> Add plugin to README

- src/chatgpt-api.ts
- src/demo-conversation.ts
Was able to make Conversation work with some trial and error.
Added a new class called `Conversation` and changed some opts of `sendMessage`, maybe not the best design so please give suggestions
Result:
(see src/demo-conversation.ts)
Before:
<details>
```ts
import dotenv from 'dotenv-safe'
import { oraPromise } from 'ora'
import { ChatGPTAPI } from '.'
dotenv.config()
/**
* Example CLI for testing functionality.
*
* ```
* npx tsx src/demo.ts
* ```
*/
async function main() {
const api = new ChatGPTAPI({ sessionToken: process.env.SESSION_TOKEN })
await api.ensureAuth()
const prompt = 'What is OpenAI?'
const response = await oraPromise(api.sendMessage(prompt, { conversationId: '0c382256-d267-4dd4-90e3-a01dd22c20a1' }), {
text: prompt
})
console.log(response)
const prompt2 = 'Continue' …
```
> Conversation support

- readme.md
Usage in CommonJS (Dynamic import):
```js
async function example() {
// use ESM in CommonJS, dynamic import
const { ChatGPTAPI } = await import('chatgpt')
// sessionToken is required; see below for details
const api = new ChatGPTAPI({ sessionToken: process.env.SESSION_TOKEN })
// ensure the API is properly authenticated
await api.ensureAuth()
// send a message and wait for the response
const response = await api.sendMessage(
'Write a python version of bubble sort. Do not include example usage.'
)
// response is a markdown-formatted string
console.log(response)
}
```
> docs: usage in CommonJS (dynamic import)

- readme.md
Add QQ bot (plugin for Yunzai) to Projects.
> Add QQ bot (plugin for Yunzai) to Projects

- readme.md
chatgpt-action is a github action that uses ChatGPT to automatically review pull requests.
> Add chatgpt-action to Projects

- readme.md
a wechat bot using wechaty, which can archive web pages, analyze pictures, and automatically reply.
> docs: Add wechat bot to readme

- readme.md
a wechat bot using wechaty , make ChatGPT more popular
> docs: add wechaty-chatgpt

- readme.md
> Add Matrix bot to readme

- readme.md
Here's a new Telegram Bot built with this project.
> docs: Add new Telegram Bot

- readme.md
Hi!
I wrote a QQ Bot with oicq and your ChatGPT-api. (with RabbitMQ)
> Add my QQ bot to Readme

- readme.md
Hi @transitive-bullshit,
Have been following this project for a couple of days now. Absolutely awesome following the fast pace journey. Kudos to you for maintaining and running this OSS project. Love it ❤️ 
My docs contribution is an AI-Generated Cover Letter Service. Would love to be featured
https://sharehouse.app/ai
Cheers
> docs: add project

- docs/classes/ChatGPTAPI.md
- docs/classes/ChatGPTConversation.md
- docs/classes/ChatGPTError.md
- docs/modules.md
- docs/readme.md
keep docs up to date, generated by npm script docs
> chore: update docs

- readme.md
Example code isn't correct. Just fixing lol.
> Fixed readme example p -> P

- readme.md
I add try again function to my bot.
> Add my bot to readme

- readme.md
Add TalkGPT to the readme file.
Easily talk to ChatGPT!
> Add TalkGPT to readme file

- src/openai-auth.ts
> fix(openai-auth.ts): fix the default chrome path of windows

- package.json
- pnpm-lock.yaml
- src/index.ts
- src/openai-auth-2captcha.ts
- src/openai-auth.ts
> feat: add 2captcha support

- readme.md
I wrote a quick one, not the best but can save people a bit of time
> Add Slack Bot to Readme

- readme.md
added my new work in progress project to the projects list
> Added new project integration to readme.md

- readme.md
added ChatGPT Figma plugin to readme.md
> Update readme.md with ChatGPT-API project

- src/openai-auth.ts
- src/utils.ts
fix: https://github.com/transitive-bullshit/chatgpt-api/issues/185
> fix: nopecha key input

- src/openai-auth.ts
- Add retry and more wait to improve robustness
- Fix https://github.com/transitive-bullshit/chatgpt-api/issues/216
- There was added retry for the function `solveRecaptchas` because it will lose Recaptchas when the network is unstable.Ï
> ⚡️ Improve robustness

- src/utils.ts
> fix JSON parse error

- readme.md
The current listed NestJS repository is very messy and includes things like a LinkedIn scraper? 🤨 So I decided to create a clean starter boilerplate that successfully imports the "chatgpt" package and does nothing else. Its solves the ERR_REQUIRE_ESM error.
> A clean NestJS starter boilerplate

- readme.md
Add my project to the project list
> feat: Add new project to readme

- package.json
- pnpm-lock.yaml
- src/chatgpt-api-browser.ts
> chore: add support for userDataDir

- readme.md
I made a small Discord bot that converts everyone's messages with a certain role to a message in the style of Shakespeare.
> Add `ShakespeareBot` to the project list

- readme.md
Hi. I built a simple Slack bot to use this lib!
> docs: add NessunKim/slack-chatgpt to README

- readme.md
This is more a 'joke' project, that uses ClippyJS as the front-end
> Add clippyJS bot to readme

- readme.md
- [Slack Bot #4](https://github.com/MarkusGalant/chatgpt-slackbot-serverless/) ( Serverless AWS Lambda )
> Add Slack Bot #4 project to readme.md

- readme.md
Hello there! 
Amazing project that you have here. I've added my npm library to the readme. It requires your amazing package for it to work.
- [ChatGPT Prompts](https://github.com/pacholoamit/chatgpt-prompts)
> Add ChatGPT prompts to Readme

- readme.md
[ai-assistant](https://github.com/youking-lib/ai-assistant) 
- Multiple prompts built-in
- Support multiple OpenAI API Keys
> Add ai-assistant project to README.md

- readme.md
Added a new project link to Readme.md file.  Thanks!
> added WhatsApp Bot #5 (RaspberryPi + ngrok + Twilio)

- src/chatgpt-api.ts
This pull request removes excessive logging to console leftover if debug is not enabled.
> Log to console only in debug mode

- readme.md
Typo demo-persistence.ts with demo-conversation.ts in the readme demo
> Update readme.md for Typo demo-persistence.ts with demo-conversation.ts in the readme demo

- demos/demo-reverse-proxy.ts
- package.json
- readme.md
- src/chatgpt-unofficial-proxy-api.ts
- src/index.ts
- src/types.ts
> feat: add ChatGPTUnofficialProxyAPI

- readme.md
> Rate limit increased

- package.json
- pnpm-lock.yaml
- src/tokenizer.ts
See my comparison & benchmark of different Node.js BPE tokenizers here: https://github.com/transitive-bullshit/compare-tokenizers
> Switch to rust wasm port of tiktoken tokenizer

- readme.md
Added my site https://aipoemgenerator.com/ to the list.
Thanks for creating that project!
> docs: add ai poem generator to projects

- readme.md
WhatsApp chatbot integrated with `MongoStore`
- stores WhatsApp client session to avoid scanning QR code every time bot starts
- saves conversation history to provide context on follow-up prompts
> Add new WhatsGPT chatbot to README.md

- package-lock.json
- package.json
Updates the token dependency that seems to be causing ENOENT issues
> fix: update tiktoken dep

- readme.md
Hi. I wrote a library which allows you to generate commits automatically using your API. The library is under MIT license and completely free, only an OpenAI key is required :)
> Add ai-commit library to projects

- bin/cli.js
> fix: can't use apiKey flag

- readme.md
Rate limits worsened due to abuse and cost
Using new bypass method
> new reverse proxy URL

- src/chatgpt-api.ts
moved /v1 to the default base url, to enable support for pawan's free api.
> moved /v1 to the default base url, to enable support for pawan's free api.

- readme.md
> docs: add one WeChat Bot to readme

- readme.md
> A small module for quick implementation of OpenAI's Chat-GPT into Discord.JS
https://github.com/Elitezen/discordjs-chatgpt
> Projects: Adding discordjs-chatgpt

- readme.md
Thanks a lot for this great and easy-to-use library!
> Added another Slack bot to the README

- readme.md
Thanks a lot for this powerful, robust and easy-to-use library!
> Add QQ Bot with Bull to Readme

- readme.md
Thanks a lot for this powerful, robust and easy-to-use library!
> add my project, a similar to chatgpt website

- package.json
- pnpm-lock.yaml
- src/tokenizer.ts
closes https://github.com/transitive-bullshit/chatgpt-api/issues/570
> switch tokenizer implementation with pure js and more compatible js-tiktoken

- readme.md
Its looks like 100% full transform language from py to go
> docs: update README for access-token library

- docs/mint.json
- docs/sdks/genaiscript.mdx
- examples/genaiscript/calculator.genai.mts
- readme.md
Adding documentation, example to use agentic with GenAIScript. No SDK needed, support is builtin.
- genaiscript + agentic docs: https://microsoft.github.io/genaiscript/guides/agentic-tools/
> add genaiscript sdk

- package.json
Making one's life easier by having a command to launch the local docs server.
> add command to launch local docs

- packages/jigsawstack/package.json
- packages/jigsawstack/src/index.ts
- packages/jigsawstack/src/integration.test.ts
- packages/jigsawstack/src/jigsawstack-client.ts
- packages/jigsawstack/src/tool.test.ts
- packages/jigsawstack/tsconfig.json
Leveraging [JigsawStack](https://jigsawstack.com/) AI SDK, this PR adds the following agent tools:
JigsawStackAIScrape - This tool enables you to scrape web content using advanced AI capabilities provided by JigsawStack.
JigsawStackAISearch - This tool allows you to perform web searches and retrieve high-quality results powered by AI.
JigsawStackSpeechToText - Transcribe video and audio files using the Whisper large V3 AI model.
JigsawStackVOCR - This tool accurately recognizes, describes, and retrieves data from images.
JigsawStackTextToSQL - This tool helps generate semantically correct SQL queries from text.
> Add JigsawStack Integration

- packages/firecrawl/package.json
- packages/firecrawl/src/firecrawl-client.ts
- packages/firecrawl/src/index.ts
- packages/firecrawl/test-firecrawl-client.ts
> [!IMPORTANT]  
> I am one of the engineers of **Firecrawl**. We are updating to the V0 API to support additional methods, as the current version will soon be deprecated. As part of this update, we are introducing several new methods for this integration and refactoring some of the existing ones.
> **Please note:** this PR includes breaking changes.
----
- Refactored `firecrawl-client.ts` to improve API request handling and added new methods for scraping, searching, crawling, and extracting data.
- Introduced comprehensive tests in `test-firecrawl-client.ts` to validate the functionality of the FirecrawlClient.
- Updated `index.ts` to export new types and the FirecrawlClient class.
> feat: update Firecrawl API version

- docs/mint.json
- docs/sdks/xsai.mdx
- docs/usage.mdx
- examples/xsai/bin/weather.ts
- examples/xsai/package.json
- examples/xsai/tsconfig.json
- packages/core/src/create-ai-function.ts
- packages/xsai/package.json
- packages/xsai/readme.md
- packages/xsai/src/index.ts
- packages/xsai/src/xsai.test.ts
- packages/xsai/src/xsai.ts
- packages/xsai/tsconfig.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
- readme.md
Adds support for the [xsAI SDK](https://github.com/moeru-ai/xsai) 🔥
cc @moeru-ai @kwaa
> Add the xsAI SDK

- packages/tool-client/src/agentic-tool-client.ts
A little help to understand how to set your token and where to get it.
> docs: enhance AgenticToolClient documentation with API key usage [AGE-44]
